add input validation
OlegKotsubko/prjctr pull request #1
Opened 2022-01-26 14:30 UTC by OlegKotsubko

## Summary
  Note title cannot be empty
  Note field limit of 1000 chars
  Show how much text input limit is exceeded
  Do not save a note if it is not valid 

## Checklist
- Try to to save notes when fields is empty
- Try to save notes when notes contain more than 1000 char
- Try to save notes when notes more than 1000 char

2022-01-27 20:28 UTC, nadiia-kobylinska commented on src/components/Form/Form.js
> +    if (editItem === null) {
Если проверка исключительно на `null` не является чем-то специфичным, то возможно есть смысл проверять все отрицательные значения, как и в строке 164. Так будет безопасней, иначе если прилетит undefined, то аппка падает.

2022-01-27 20:28 UTC, nadiia-kobylinska commented on src/components/Form/Form.js
> +      clearHandler()
clearHandler() дублируется в 130 строке, думаю есть смысл вынести вне IF

2022-01-27 20:28 UTC, nadiia-kobylinska commented on src/components/Form/Form.js
> +          description: inputValues.description,
Возможно есть вариант как более оптимально передавать данные в payload и не загружать множеством параметров. 
Если нужно будет добавить ещё 10 полей, то все их нужно будет повсюду продублировать.

2022-01-28 10:21 UTC, Rastopyr requested changes

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +  });
Если я правильно понимаю: то это в стейте нам не требуется.
Валидация может считаться просто на каждый рендер компонента.

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +      });
Можно initial state в хуке useState пробросить не используя эффект

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +        inputValues.title?.length > MAX_TITLE_LENGTH
Если я правильно понимаю: то это в стейте нам не требуется.
Валидация может считаться просто на каждый рендер компонента.

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +    setInputValues({
Я бы предложил заинлайнить reset состояния в submitHanlder

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +        title: 'Plz fill this field'
Тут проблема, что если сначала будет не валидный description а потом юзер удалит title, то ошибка с тайтлом перетрет ошибку description.

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +      || inputValues.description?.length > MAX_DESCRIPTION_LENGTH
А зачем тут используетя optional chaining? title и description могут быть undefined?

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +  } = useContext(NoteContext);
Я бы вынес эту логику на слой выше, но предложил бы сделать это в рамках другого ПР и следующей домашки. Тут просто акцентирую внимание на этом)

2022-01-28 10:21 UTC, Rastopyr commented on src/components/Form/Form.js
> +    const { name, value } = e.target;
Мне кажется что стоит сделать два отдельных хендлера для каждого из обработчиков. Тут целевое поле сильно завязано на какой то атрибут который должен совпадать с полем в стейте. Это сложно затипизировать и затестить.

2022-01-28 10:25 UTC, Rastopyr commented
Я бы хотел еще тебя попросить немного детализировать описание ПР :)

Можно использовать советы из [гайда который я скидывал в Slack](https://oumaima-dahhoum.medium.com/how-to-create-a-good-pull-request-with-examples-and-templates-cfc92f2bb94e).

Или же можно использовать шаблон из трех вопросов.
 * Что? - Что именно содержит этот ПР? какую задачу он решает?
 *  Как? - Как конкретно решается выше описанная задача?
 *  Почему? - Почему используется именно это решение? Почему оно наиболее оптимальное?

Спасибо!

2022-01-28 15:31 UTC, OlegKotsubko commented
## Summary
  Note title cannot be empty
  Note field limit of 1000 chars
  Show how much text input limit is exceeded
  Do not save a note if it is not valid 

## Checklist
- Try to to save notes when fields is empty
- Try to save notes when notes contain more than 1000 char
- Try to save notes when notes more than 1000 char

2022-01-30 14:49 UTC, Rastopyr requested changes

2022-01-30 14:49 UTC, Rastopyr commented on src/components/Form/Form.js
> +  const [titleError, setTitleError] = useState('');
Эти стейты тут не нужны. Они только усложняют логику компонента.

Смотри, есть какие то правила валидации которые пересчитываются, если меняется title,setTitile. Правила валидации не должны дополнительно форсировать рендеринг(по крайней мере в этом компоненте).

Давай попробуем начать с того, что нужно определить две переменные, которые называются `isTitleValid`, `isDescriptionValid`. Как они будут обсчитываться?

2022-01-30 14:49 UTC, Rastopyr commented on src/components/Form/Form.js
> +    if(title.length > MAX_TITLE_LENGTH) {
Представь что правила валидации могут поменяться. Удобно ли будет в менять каждый раз в компоненте? Если правил валидации будет больше, удобно ли их описывать внутри if? Давай подумаем как это можно переписать по другому, чтобы сделать код более поддерживаемым

2022-01-30 14:49 UTC, Rastopyr commented on src/components/Form/Form.js
> +      setDescriptionError('Plz fill this field');
Я не уверен что submitHanlder должен управлять состоянием ошибок

2022-01-30 14:49 UTC, Rastopyr commented on src/components/Form/Form.js
> +    if(!descriptionError && !titleError && title !== '' && description !== '') {
Тут должно быть два флага, `isTitleValid`, `isDescriptionValid`. Выше уже описал пару проблем потенциальных, что валидаций может стать больше, а в коде компонента несколько мест где правила валидации инлайнятся.

2022-01-30 14:49 UTC, Rastopyr commented on src/components/Form/Form.js
> +    if(!descriptionError && !titleError && title !== '' && description !== '') {
Если по научному, то тут нарушается Open/Closed Principle. Правила валидации компонента закрыты для расширения, но открыты для изменения.

То есть мы не можем добавить новые правила валидации, не меняя код компонента. А по хорошему должно быть наборот. Ну и логика одинаковая, из одного домена дублируется несколько раз.

2022-01-30 14:49 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          <Note
Мне кажется название лучше подходит `NoteListItem`

2022-01-30 15:37 UTC, OlegKotsubko commented on src/components/Form/Form.js
> +      });
Это я пробрасываю данные для того чтобы редактировать заметку. Это не initial state, потому использую внутри useEffect. Это если я понял суть коммента)

2022-01-30 16:06 UTC, OlegKotsubko commented on src/components/Form/Form.js
> +    setInputValues({
Да, но я использую эту функцию 2 раза. Потому хотел бы оставить

2022-01-31 12:09 UTC, nadiia-kobylinska approved these changes

2022-01-31 15:23 UTC, OlegKotsubko commented on src/components/Form/Form.js
> +      setDescriptionError('Plz fill this field');
Я хочу показать ошибки под каждым полем, если юзер пытается нажать submit при пустых полях. Потому сделал дополнительный стейт для ошибок.

2022-02-01 09:15 UTC, Rastopyr commented on src/components/Form/Form.js
> +      setDescriptionError('Plz fill this field');
Давай сделаем вычисление ошибок без стейта. Можно сотавить флажочек на `erorrisIsVisible` например и по нему показывать. Сейчас onSubmitHanlder слишком нагруженный, а логика валидации разамзана по компоненту.

2022-02-02 08:20 UTC, OlegKotsubko commented on src/components/Form/Form.js
> +      });
я понял, что это нужно пробрасыввать в компоненте выше.

2022-02-02 22:30 UTC, Rastopyr requested changes

2022-02-02 22:30 UTC, Rastopyr commented on src/helpers/isTitleValid.js
> +    console.log(`Title is more then ${Number(title.length) - (MAX_TITLE_LENGTH)}`)
Можешь пожалуйста рассказать в чем заключается смысл этого метода?

Я в прошлом request to change предлагал вынести логику валидации в метод и переиспользовать его. Сеейчас получается что это просто логгер, который ни на что не влияет.

2022-02-02 22:30 UTC, Rastopyr commented on src/helpers/isDescriptionValid.js
> +const isDescriptionValid = (description) => {
Я в прошлом request to change предлагал вынести логику валидации в метод и переиспользовать его. Сеейчас получается что это просто логгер, который ни на что не влияет.

2022-02-02 22:30 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +            noteRemoveHandler={removeNote(dispatch)}
Там уже есть в контексте removeNote, стоит disptach убрать а использовать уже готовый action creator

2022-02-02 22:30 UTC, Rastopyr commented on src/components/Note/Note.js
> +                  noteRemoveHandler(id)
давай сделаем более чистым контракт и назовем метод onDelete

2022-02-02 22:30 UTC, Rastopyr commented on src/App.js
> +            formSubmitHandler={editNote(dispatch)}
В контексте уже есть editNote, addNote методы, предлагаю использовать их

2022-02-02 22:30 UTC, Rastopyr commented on src/components/Form/Form.js
> +    if(title !== '' && description !== '') {
Тут не проверяется логика на валидность. Если я напишу большой тайтл или дескрипшн, эта логика позволит мне это сделать.

Вот те хелперы, которые логируют по правилам, должны проверять и на длину и на пустое значение, и возвращать true/false.

Данный компонент должен использовать эти компоненты для определения флагов `isValidTitle`/`isValidDescription` а внутри обработчика эти флаги должны использоваться для проверки.

2022-02-02 22:30 UTC, Rastopyr commented on src/components/Form/Form.js
> +      setDescription('')
Дублируется в двух местах.
Раньше это был метод который можно было переиспользовать. Ты писал что хотел его оставить, почему убрал?

2022-02-03 12:37 UTC, OlegKotsubko commented on src/components/Form/Form.js
> +      setDescription('')
Согласен) Тут скорей всего увлекся чисткой ненужных функций

2022-02-03 12:37 UTC, OlegKotsubko commented on src/helpers/isTitleValid.js
> +    console.log(`Title is more then ${Number(title.length) - (MAX_TITLE_LENGTH)}`)
я пытаюсь придумать как использовать этот валидатор, для показа ошибок. Пока без результатов.

2022-02-08 14:43 UTC, Rastopyr commented
Спасибо что бьешь на коммиты! Намного удобнее читать и давать фидбек!

2022-02-08 14:44 UTC, Rastopyr approved these changes

2022-02-08 14:45 UTC, Rastopyr commented
Хороший прогресс! Двигаемся дальше!

2022-02-08 16:24 UTC, merged