Feature/create context for view mode
OlegKotsubko/prjctr pull request #3
Opened 2022-02-09 12:30 UTC by OlegKotsubko

## Added app state management for Edit  and Preview modes

## Checklist
- ViewModeContextProvider code base
- delete Note while editing
- delete Note while preview mode

2022-02-14 16:29 UTC, Rastopyr requested changes

2022-02-14 16:29 UTC, Rastopyr commented on src/App.js
> +    case "PREVIEW":
Тут лучше использовать не строковые литералы, а константы или вообще описать возможные режимы объектом. Это проще поддерживать и менять.

\+ если будет система типов(flow, typescript) то switch будет еще типизированный

2022-02-14 16:29 UTC, Rastopyr commented on src/App.js
> +        <FormContainer
Давай для формы пропишем отдельный мод явно?

2022-02-14 16:29 UTC, Rastopyr commented on src/actions/view-actions.js
> +export const SET_PREVIEW = "SET_PREVIEW"
`SET_PREVIEW` -> `SET_PREVIEW_ROUTE_MODE`
`SET_EDIT` -> `SET_EDIT_ROUTE_MODE`
`SET_DEFAULT` -> `SET_DEFAULT_ROUTE_MODE`

2022-02-14 16:29 UTC, Rastopyr commented on src/actions/view-actions.js
> +export const setPreview = (dispatch) => () =>
`setPreview` -> `setPreviewMode`
`setEdit` -> `setEditMode`
`setDefault` -> `setDefaultMode`

2022-02-14 16:29 UTC, Rastopyr commented on src/components/FormContainer/FormContainer.js
> +        <Form
Тут лучше использовать не строковые литералы, а константы или вообще описать возможные режимы объектом. Это проще поддерживать и менять.

\+ если будет система типов(flow, typescript) то switch будет еще типизированный

2022-02-14 16:29 UTC, Rastopyr commented on src/contexts/ViewModeContext.js
> +    onPreview: setPreview(dispatch),
Именование `onWhatever` лучше использовать когда речь идет про событие. В данном случае речь идет про API. Тут лучше подойдет императивное именование `setPreviewMode` или `goToPreview`

2022-02-14 16:29 UTC, Rastopyr commented on src/contexts/ViewModeContext.js
> +      modeActions,
`modeActions` -> `actions`

2022-02-15 18:07 UTC, OlegKotsubko commented on src/contexts/ViewModeContext.js
> +      modeActions,
<img width="239" alt="Screenshot 2022-02-15 at 20 06 07" src="https://user-images.githubusercontent.com/18003430/154122333-d8ab3368-1cab-44fa-8138-58b02cd85045.png">
если использовать два хука рядом будет конфликт имен или придется писать `actions: modeActions`

2022-02-16 08:44 UTC, Rastopyr commented on src/contexts/ViewModeContext.js
> +      modeActions,
> если использовать два хука рядом будет конфликт имен или придется писать `actions: modeActions` 

Да, консьюмер уже должен соответствующим образом называть поля и методы

2022-02-16 10:12 UTC, Rastopyr requested changes

2022-02-16 10:12 UTC, Rastopyr commented on src/reducer/view-reducer.js
> +export const MODE = {
`MODE` -> `VIEW_MODE`

2022-02-16 10:12 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          notesActions={notesActions}
Зачем сюда передается notesActions?

2022-02-16 10:12 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          notesActions={notesActions}
Тоже самое про viewModelActions

2022-02-16 10:12 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          deleteActiveNote={deleteActiveNote}
`onDelete`

2022-02-16 10:12 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          setActiveNoteById={setActiveNoteById}
`onActivate`

2022-02-16 10:12 UTC, Rastopyr commented on src/components/NotesList/NotesList.js
> +          noteRemoveHandler={noteRemoveHandler}
onRemove

2022-02-20 13:18 UTC, Rastopyr approved these changes

2022-02-20 13:24 UTC, merged